# Data Profiling

In this notebook, we will explore the freelancers data sourced from [here](https://www.kaggle.com/datasets/princekhunt19/700-jobs-data-of-ai-and-data-fields-2025). We will
- Understand its components.
- Clean any bad data.
- Extract the relevant subsets.
- Standardize the data structure to feed it to a RAG system.

**Sections**  
- [Setup](#Setup)
- [Basic Exploration](#Basic-Exploration)
- [Cleaning](#Cleaning)

---
---

## Setup

**Importing Dependecies**

In [1]:
import numpy as np
import pandas as pd
import os

**Define Options & Paths**

In [2]:
pd.set_option('display.max_columns', None)

data_path = 'data/jobs_dataset.csv'

---
---

## Basic Exploration

In [3]:
df1 = pd.read_csv(data_path)
df1.head()

,company,rating,location,positionName,description,salary,url,jobType/0,jobType/1,jobType/2,jobType/3,searchInput/country,searchInput/position,externalApplyLink
0,Google,4.3,"San Bruno, CA","Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,"$166,000 - $244,000 a year",https://www.indeed.com/viewjob?jk=3129ec5dde24...,Full-time,NaN,NaN,NaN,US,Data Scientist,https://www.google.com/about/careers/applicati...
1,BAXTER,3.7,"Milwaukee, WI 53214",Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,"$112,000 - $154,000 a year",https://www.indeed.com/viewjob?jk=19da1b85455c...,Full-time,NaN,NaN,NaN,US,Data Scientist,https://jobs.baxter.com/en/job/-/-/152/8298788...
2,Meta,4.2,"Redmond, WA","Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",$70.67 an hour,https://www.indeed.com/viewjob?jk=0b0b432e2a51...,Full-time,NaN,NaN,NaN,US,Data Scientist,https://www.metacareers.com/jobs/3101204833367...
3,Meta,4.2,"Bellevue, WA 98005","Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...","$203,350 - $240,240 a year",https://www.indeed.com/viewjob?jk=08d2ef77c976...,Full-time,NaN,NaN,NaN,US,Data Scientist,https://www.metacareers.com/jobs/1096352489054...
4,Lockheed Martin,4.0,"Shelton, CT 06484",AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",NaN,https://www.indeed.com/viewjob?jk=e9aad7dcc34e...,Full-time,NaN,NaN,NaN,US,Data Scientist,https://click.appcast.io/t/V35efAz0-l7FWwo6IKe...

In [4]:
# remove irrelevant / redundant cols
relevant_cols = [
    'positionName', 
    'description', 
    'searchInput/position',
]

df1 = df1.copy()[relevant_cols]

df1.head()

,positionName,description,searchInput/position
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,Data Scientist
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,Data Scientist
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",Data Scientist
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",Data Scientist
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",Data Scientist

In [5]:
df1.shape

(735, 3)

---
---

## Cleaning

**Addressing nulls & duplicates**

In [6]:
df1.isna().sum()

positionName            0
description             0
searchInput/position    0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(23)

In [8]:
df1.drop_duplicates(inplace = True)

df1.shape

(712, 3)

**Clean Names**

In [9]:
names_dict = {
    'positionName' : 'title',
    'searchInput/position' : 'category'
}
df1.rename(columns = names_dict, inplace = True)
df1.head()

,title,description,category
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,Data Scientist
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,Data Scientist
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",Data Scientist
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",Data Scientist
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",Data Scientist

In [10]:
# add the year
df1['year'] = 2025
df1.head()

,title,description,category,year
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,Data Scientist,2025
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,Data Scientist,2025
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",Data Scientist,2025
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",Data Scientist,2025
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",Data Scientist,2025

**The `description` column**

In [13]:
def print_job_descriptions(descriptions, n_sep = 100):
    for idx, desc in enumerate(descriptions):
        print(f'>> Job #_{idx}')
        print()
        print(desc)
        print()
        print('-' * n_sep)

In [14]:
# explore samples
descs = df1.description.values.tolist()
print_job_descriptions(descs[:5])

>> Job #_0

Note: By applying to this position you will have an opportunity to share your preferred working location from the following: San Bruno, CA, USA; Mountain View, CA, USA.
Minimum qualifications:
Master's degree in Statistics, Data Science, Mathematics, Physics, Economics, Operations Research, Engineering, or a related quantitative field or equivalent practical experience.
5 years of experience using analytics to solve product or business problems, coding (e.g., Python, R, SQL), querying databases or statistical analysis, or 3 years of work experience with a PhD degree.

Preferred qualifications:
8 years of work experience using analytics to solve product or business problems, coding (e.g., Python, R, SQL), querying databases or statistical analysis, or 6 years of work experience with a PhD degree.
About the job
In this role, you will develop statistical solutions to common problems faced by YouTube (YT) Search. The role also involves participating in experiments to understand issues, and contributing to foundational improvements in data quality.

The US base salary range for this full-time position is $166,000-$244,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.

Please note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google.
Responsibilities
Collaborate with stakeholders in cross-projects and team settings to identify business or product questions to answer. Provide feedback to translate business questions into analysis, evaluation metrics, or mathematical models.
Use custom data infrastructure or existing data models. Design and evaluate models to mathematically express and solve defined problems.
Gather information, business goals, priorities, and organizational context around the questions to answer, as well as the existing and upcoming data infrastructure.
Own the process of gathering, extracting, and compiling data across sources via tools (e.g., SQL, R, Python). Format, re-structure, or validate data to ensure quality, and review the dataset to ensure it is ready for analysis.
Google is proud to be an equal opportunity workplace and is an affirmative action employer. We are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity or Veteran status. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements. See also Google's EEO Policy and EEO is the Law. If you have a disability or special need that requires accommodation, please let us know by completing our Accommodations for Applicants form.

----------------------------------------------------------------------------------------------------
>> Job #_1

This is where you save and sustain lives

At Baxter, we are deeply connected by our mission. No matter your role at Baxter, your work makes a positive impact on people around the world. You’ll feel a sense of purpose throughout the organization, as we know our work improves outcomes for millions of patients.

Baxter’s products and therapies are found in almost every hospital worldwide, in clinics and in the home. For over 85 years, we have pioneered significant medical innovations that transform healthcare.

Together, we create a place where we are happy, successful and inspire each other. This is where you can do your best work.

Join us at the intersection of saving and sustaining lives— where your purpose accelerates our mission.

Your Role at Baxter:

We are looking for a Sr AI Engineer (Data Scientist) that can grow, tackle, drive, and build data products to support the Connected solutions portfolio within Baxter.

Your Team:

This role is a part of the Innovation, Strategy and Data science team within the Digital Platform and Innovation group responsible for bringing data science and machine learning ideas to life at Baxter

What You'll Be Doing:

Responsible for the development and implementation of predictive modeling algorithms and techniques to address unmet needs, customer/business problems and optimize user experiences.

Conduct in-depth research to stay at the forefront of AI advancements, exploring opportunities to integrate predictive and generative AI models into our products and services.

Predictive and generative AI Modeling.

Formulate problem statements and hypotheses for diverse business challenges (clinical, operational and business process optimization problems).

Create Spark & Python code in Databricks to retrieve data from across disparate data sources and create new innovative actionable insights.

Prepare data for effective model training.

Develop, train, and evaluate predictive AI models using various tailored to specific problems.

Continuously refine and optimize models for performance, scalability, and efficiency.

Deploy models into production environments and supervise their performance.

Identify opportunities where generative AI models can add value.

Explore and experiment with generative models (e.g., GPT) suitable for the chosen application.

Train and evaluate generative models, fine-tuning parameters for desired outputs.

Integrate generative models into production workflows or applications.

Work with data-sets of varying degrees of size and complexity including both structured and unstructured data.

Implements batch and real-time model scoring to drive actions.

Develop sophisticated visualization of analysis output for various users.

Determines the continuous improvement opportunities of current predictive modeling algorithms.

Innovate and engage with key technology stakeholders to create a compelling vision of a data-driven enterprise environment and the impact it will have on their teams, their projects and their outcomes.

What You'll Bring:

Bachelor’s Degree in STEM (science, technology, engineering, math) related field or a similar quantitative analytics field.

4+ years of professional experience with a variety of data products / data science model / algorithm development and implementing in production.

Software development experience.

Experience with healthcare data and working in a HIPAA regulated environment preferred.

Experience with varying database structures and large datasets preferred.

Experience with modern data science tools; their primary stack is Spark, Scala, Python, Databricks, and more.

Experience in Microsoft Azure cloud environment is preferred.

Proficiency with developing data visualization technology and capabilities (i.e., Power BI, Tableau).

Brings a drive for creatively applying pragmatic and scalable approaches to Machine Learning to tackle difficult problems affecting patients and providers.

Passionate about working on a high-performance team toward a multi-year vision with incremental deliverables.

Entrepreneurial self-starter, curious about both technology and business, and driven by delivering end-user value and impact.

We understand compensation is an important factor as you consider the next step in your career. At Baxter, we are committed to equitable pay for all employees, and we strive to be more transparent with our pay practices. The estimated base salary for this position is $112,000.00 to $154,000.00 annually. The estimated range is meant to reflect an anticipated salary range for the position. We may pay more or less than of the anticipated range based upon market data and other factors, all of which are subject to change. Individual pay is based on upon location, skills and expertise, experience, and other relevant factors. For questions about this, our pay philosophy, and available benefits, please speak to the recruiter if you decide to apply and are selected for an interview.

Applicants must be authorized to work for any employer in the U.S. We are unable to sponsor or take over sponsorship of an employment visa at this time.

US Benefits at Baxter (except for Puerto Rico)

This is where your well-being matters. Baxter offers comprehensive compensation and benefits packages for eligible roles. Our health and well-being benefits include medical and dental coverage that start on day one, as well as insurance coverage for basic life, accident, short-term and long-term disability, and business travel accident insurance. Financial and retirement benefits include the Employee Stock Purchase Plan (ESPP), with the ability to purchase company stock at a discount, and the 401(k) Retirement Savings Plan (RSP), with options for employee contributions and company matching. We also offer Flexible Spending Accounts, educational assistance programs, and time-off benefits such as paid holidays, paid time off ranging from 20 to 35 days based on length of service, family and medical leaves of absence, and paid parental leave. Additional benefits include commuting benefits, the Employee Discount Program, the Employee Assistance Program (EAP), and childcare benefits. Join us and enjoy the competitive compensation and benefits we offer to our employees. For additional information regarding Baxter US Benefits, please speak with your recruiter or visit our Benefits site: Benefits | Baxter

Equal Employment Opportunity

Baxter is an equal opportunity employer. Baxter evaluates qualified applicants without regard to race, color, religion, gender, national origin, age, sexual orientation, gender identity or expression, protected veteran status, disability/handicap status or any other legally protected characteristic.

Know Your Rights: Workplace Discrimination is Illegal

Reasonable Accommodations

Baxter is committed to working with and providing reasonable accommodations to individuals with disabilities globally. If, because of a medical condition or disability, you need a reasonable accommodation for any part of the application or interview process, please click on the link here and let us know the nature of your request along with your contact information.

Recruitment Fraud Notice

Baxter has discovered incidents of employment scams, where fraudulent parties pose as Baxter employees, recruiters, or other agents, and engage with online job seekers in an attempt to steal personal and/or financial information. To learn how you can protect yourself, review our Recruitment Fraud Notice.

----------------------------------------------------------------------------------------------------
>> Job #_2

Redmond, WA • + 2 more•Full Time
Messenger
Messenger
Instagram
Generative AI
Facebook
Artificial Intelligence
AR/VR
Research
Software Engineering
Engineering
Machine Learning
Research
Artificial Intelligence

At Meta, we're building products that revolutionize the way people connect, work, and play. Our audio teams are at the forefront of this innovation, developing cutting-edge technologies that redefine the way we experience sound in virtual and augmented worlds.

Our teams are dedicated to creating a considerate and honest environment where self-motivated individuals thrive. We encourage ownership, creativity, and collaboration, and we're passionate about making science fiction real.

Join us on this adventure: As a member of our audio team, you'll be part of a community that's shaping the future of sound and connection. Together, let's invent the future and change the world.
Audio Software Engineer, Applied Scientist Responsibilities
Collaborate in a team environment across multiple scientific and engineering disciplines, making the architectural tradeoffs required to rapidly deliver software solutions
Create clean readable code, debug complex problems, prioritize ruthlessly and get things done with a high level of efficiency
Learn constantly, dive into new areas with unfamiliar technologies, and embrace the ambiguity of problem solving
Develop audio software for a variety of consumer products and devices
Minimum Qualifications
Bachelor's degree in Computer Science, Computer Engineering, relevant technical field, or equivalent practical experience
5+ years software development experience in industry settings or PhD with 2+ years of experience
3+ years relevant audio software engineering experience in industry settings
C or C++ experience, including use of C++11/14/17 features
Communication experience and demonstrated experience working across disciplines to drive optimal solutions
Preferred Qualifications
Expertise in audio signal processing and auditory perception, both classical and machine learned techniques
Experience with audio stack including codecs, audio capture/render, and network compensation/jitter buffer
Proven track record of innovation as demonstrated by products shipped, publications and/or patents
Experience with GenAI
For those who live in or expect to work from California if hired for this position.
About Meta
Meta builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps like Messenger, Instagram and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology. People who choose to build their careers by building with us at Meta help shape a future that will take us beyond what digital connection makes possible today—beyond the constraints of screens, the limits of distance, and even the rules of physics.

$70.67/hour to $208,000/year + bonus + equity + benefits

Individual compensation is determined by skills, qualifications, experience, and location. Compensation details listed in this posting reflect the base hourly rate, monthly rate, or annual salary only, and do not include bonus, equity or sales incentives, if applicable. In addition to base compensation, Meta offers benefits. Learn more about benefits at Meta.

Equal Employment Opportunity
Meta is proud to be an Equal Employment Opportunity employer. We do not discriminate based upon race, religion, color, national origin, sex (including pregnancy, childbirth, reproductive health decisions, or related medical conditions), sexual orientation, gender identity, gender expression, age, status as a protected veteran, status as an individual with a disability, genetic information, political views or activity, or other applicable legally protected characteristics.
Meta is committed to providing reasonable accommodations for qualified individuals with disabilities and disabled veterans in our job application procedures.

----------------------------------------------------------------------------------------------------
>> Job #_3

Bellevue, WA • Full Time
Meta
Software Engineering
Engineering

Meta Platforms, Inc. (Meta), formerly known as Facebook Inc., builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps and services like Messenger, Instagram, and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology.
Software Engineer, Machine Learning Responsibilities
Research, design, develop, and test operating systems-level software, compilers, and network distribution software for massive social data and prediction problems.
Have industryexperience working on a range of ranking, classification, recommendation, and optimization problems, e.g. payment fraud, click-through or conversion rate prediction, click-fraud detection, ads/feed/search ranking, text/sentiment classification, collaborative filtering/recommendation, or spam detection.
Working on problems of moderate scope, develop highly scalable systems, algorithms and tools leveraging deep learning, data regression, and rules based models.
Suggest, collect, analyze and synthesize requirements and bottleneck in technology, systems, and tools.
Develop solutions that iterate orders of magnitude with a higher efficiency, efficiently leverage orders of magnitude and more data, and explore state-of-the-art deep learning techniques.
Receiving general instruction from supervisor, code deliverables in tandem with the engineering team.
Adapt standard machine learning methods to best exploit modern parallel environments (e.g. distributed clusters, multicore SMP, and GPU).
Minimum Qualifications
Requires a Master’s degree in Computer Science, Computer Software, Computer Engineering, Applied Sciences, Mechanical Engineering, Mathematics, Physics, or related field and threeyears of work experience in the job offered or in a computer-related occupation
Requires three years of experience in the following:
1. Machine Learning Framework(s): PyTorch, MXNet, or Tensorflow
2. Machine learning, recommendation systems, computer vision, natural language processing, data mining, or distributed systems
3. Translating insights into business recommendations
4. Hadoop, HBase, Pig, MapReduce, Sawzall, Bigtable, or Spark
5. Developing and debugging in C, C++, and Java
6. Scripting languages: Perl, Python, PHP, or shell scripts
7. C, C++, C#, or Java
8. Python, PHP, or Haskell
9. Relational databases and SQL
10. Software development tools: Code editors (VIM or Emacs), and revision control systems (Subversion, GIT, or Perforce)
11. Linux, UNIX, or other *nix-like OS as evidenced by file manipulation, advanced commands, and shell scripting
12. Build highly-scalable performant solutions
13. Data processing, programming languages, databases, networking, operating systems, computer graphics, or human-computer interaction
14. Applying algorithms and core computer science concepts to real world systems as evidenced by recognizing and matching patterns from different areas of computer science in production systems
15. Distributed systems
For those who live in or expect to work from California if hired for this position.
About Meta
Meta builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps like Messenger, Instagram and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology. People who choose to build their careers by building with us at Meta help shape a future that will take us beyond what digital connection makes possible today—beyond the constraints of screens, the limits of distance, and even the rules of physics.

$203,350/year to $240,240/year + bonus + equity + benefits

Individual compensation is determined by skills, qualifications, experience, and location. Compensation details listed in this posting reflect the base hourly rate, monthly rate, or annual salary only, and do not include bonus, equity or sales incentives, if applicable. In addition to base compensation, Meta offers benefits. Learn more about benefits at Meta.

Equal Employment Opportunity
Meta is proud to be an Equal Employment Opportunity employer. We do not discriminate based upon race, religion, color, national origin, sex (including pregnancy, childbirth, reproductive health decisions, or related medical conditions), sexual orientation, gender identity, gender expression, age, status as a protected veteran, status as an individual with a disability, genetic information, political views or activity, or other applicable legally protected characteristics.

In [15]:
def get_description_lengths(desc: str):
    words = desc.split()
    return len(words)

In [16]:
df1['description_lengths'] = df1.description.apply(get_description_lengths)

df1.head()

,title,description,category,year,description_lengths
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,Data Scientist,2025,447
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,Data Scientist,2025,1083
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",Data Scientist,2025,573
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",Data Scientist,2025,692
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",Data Scientist,2025,863

In [18]:
df1.description_lengths.describe()

count     712.000000
mean      747.932584
std       332.911697
min        19.000000
25%       537.000000
50%       714.000000
75%       911.500000
max      2621.000000
Name: description_lengths, dtype: float64

In [20]:
df1.sort_values(by = ['description_lengths'])['description_lengths'].head(n = 20)

324     19
498     70
84      72
675     73
164     96
270    108
276    113
482    121
105    156
519    175
503    178
573    186
700    188
433    195
501    196
330    210
242    212
452    212
33     214
664    218
Name: description_lengths, dtype: int64

In [27]:
filt = df1['description_lengths'] <= 100
descs = df1[filt].description.values.tolist()

In [28]:
print_job_descriptions(descriptions = descs)

>> Job #_0

*S*enior ML Engineer

*Must Have Tool Stack and Design Paradigm:*

* Python, YAML

* Azure Cloud Services

* MongoDB, NOSQL expertise

* Redis Caching

* Seldon Framework, API Management

* Microservices architecture

* DataDog monitoring

* PySpark Framework

* JSON data structure and integration

* Streamlit frontend

Job Type: Contract

Pay: $60.00 - $70.00 per hour



Application Question(s):
* Do you have experience with Azure, Python, Yaml and Datadog?

Work Location: Remote

----------------------------------------------------------------------------------------------------
>> Job #_1

Job Title :Gen AI Architect

Location: Oak Park, IL

Duration: Long term

Responsibilities:

* *Should be really good with prompt engineering and with integration exp. with services and monitoring tools like Dynatrace or any other. *
* *Netomi is preferred only.*

*Should be good with Coversational AI & Cloud Contact Center exp.*

Gen AI Components (Conversation)
   Prompt Components
   Services
   Configuring and Establishing
     Dynatrace or any other monitoring tool
     Netomi and LivePerson
   CC capabilities
   Dashboard (Netomi and LivePerson)

Job Type: Contract

Schedule:
* 8 hour shift
* Day shift
* Monday to Friday

Work Location: In person

----------------------------------------------------------------------------------------------------
>> Job #_2

Role: Senior Data Analyst with strong SAS programming and SQL Duration: 6+ months Location: Irving Place, New York, NY(Local)

----------------------------------------------------------------------------------------------------
>> Job #_3

Engagement Type

Contract

Required/Desired Skills
Skill Required/Desired Amount of Experience Experience using Impala/ANSI SQL to select and transform data as needed. SQL experience must include data conversion, pivots, and logical assignments Required 0 Experience using Hue (Impala Editor) for querying large datasets, managing SQL scripts, and creating reusable query workflows Required 0 Experience collecting and managing WIC data from Client WIC agency via the Innovation Client Platform (IOP). Required 0

----------------------------------------------------------------------------------------------------
>> Job #_4

*AI/ML Developer with Cybersecurity Exposure*
*Onsite - Charlotte, NC*
*Long Term*
*Work Authorization: Open to OPT, W2, or C2C (Strong Profiles Only)*


*Required Skills:*
* 6–7+ years of experience in AI/ML development
* Strong Python and ML libraries (e.g., scikit-learn, TensorFlow, PyTorch)
* Experience with cybersecurity tools, threat modeling, or SIEM data
* Familiarity with cloud platforms (AWS/Azure/GCP) is a plus

Job Type: Contract

Schedule:
* 8 hour shift

Work Location: In person

----------------------------------------------------------------------------------------------------

**The `title` column**

In [30]:
df1.title.nunique()

550

In [32]:
df1.title.value_counts().head(n = 30)

title
Data Scientist                                                             45
Senior Data Scientist                                                      15
Senior Data Analyst                                                        12
Lead Data Scientist                                                         7
AI/ML Engineer                                                              6
Principal Data Scientist                                                    6
Machine Learning Engineer                                                   6
AI Engineer                                                                 5
Sr. Data Scientist                                                          5
Senior Machine Learning Engineer                                            5
Data Scientist II                                                           4
Sr Data Scientist                                                           3
Principal Statistical Programmer                                            3
ML Engineer                                                                 3
Machine Learning Scientist                                                  3
Data Scientist III                                                          3
Senior AI Engineer                                                          3
Software Engineer, Machine Learning                                         3
AI Developer                                                                2
AI Solutions Architect                                                      2
Lead Machine Learning Engineer                                              2
AI & Data Manager - Life Sciences R&D (CMC)                                 2
AI & Data Platform Program Lead - SVP                                       2
Sr. Data Scientist, ART19                                                   2
Applied Scientist I, Buyer Abuse Prevention                                 2
Data Science Engineer                                                       2
Software Dev Engineer II, Measurement, Ad Tech, and Data Science (MADS)     2
Senior Delivery Consultant- GenAI/ML, AWS, Industries                       2
Machine Learning Engineer - Vice President                                  2
Deep Learning Architect, Generative AI Innovation Center                    2
Name: count, dtype: int64

In [33]:
df1.title.value_counts().tail(n = 30)

title
Product Engineer, AI Innovation                                                     1
Principal Threat Researcher (Data Platform)                                         1
Senior Machine Learning Operations (MLOps) Engineer                                 1
Data Scientist (REMOTE)- Veterans Affairs                                           1
Senior Manager, Data Science - GenAI Digital Assistant                              1
Data Literacy Lead-Data Solutions (San Antonio, Austin and Dallas)                  1
Head of Robotics & Applied AI                                                       1
Applied Scientist III, AWS Elemental MediaConvert                                   1
Software Engineer with ML/AI (not looking for Data Scientist)                       1
Artificial Intelligence Developer with Drools                                       1
Senior Staff Machine Learning Engineer, Ads Technology (Hybrid)                     1
Artificial Intelligence Specialist - Multimedia - Fort Liberty, North Carolina      1
AI Solutions Engineer                                                               1
Data Scientist with expertise in DOMO and Python                                    1
Machine Learning Engineer - AI Trainer                                              1
RFP & Proposal Specialist (AI-Enabled)                                              1
FSP Principal Statistical Programmer (Remote)                                       1
FinTech Product Analyst - AI Trainer                                                1
Director, Data Science Platform | Data Science Platform                             1
Senior Applied Scientist – Legal Tech                                               1
Lead Applied ML Engineer, Remote, Technology & Digital,M-F 8:30A to 4:30P           1
Director of Research, Autonomy & Trusted AI                                         1
Senior AI Engineer - AI Incubation                                                  1
AI Engineer (Unable to consider OPT/CPT candidates)                                 1
Lead Machine Learning Engineer - ESPN+ Personalization                              1
VP - Regulatory Reporting Ld Analyst / Data Scientist - TAMPA/CHARLOTTE (Hybrid)    1
Machine Learning Engineer, Specialist                                               1
Domain Architect- AI/ML, Senior Specialist                                          1
Data Analytics Consultant                                                           1
Staff Data Scientist, Research, Search Platforms                                    1
Name: count, dtype: int64

**The `category` col**

In [34]:
df1.category.nunique()

1

In [36]:
df1.category.value_counts()  # only Data Scientist exists!

category
Data Scientist    712
Name: count, dtype: int64

**Finalize Data**

In [41]:
df1 = df1.copy().drop(columns = ['category', 'description_lengths'])
df1.head()

,title,description,year
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,2025
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",2025

In [44]:
# save
df1.to_csv("data/jobs_1_cleaned.csv", index = False)

---
---

***ALHAMDULILLAH***